[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
; Enable USB Serial JTAG for USB-C serial console
build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    t-vk/ESP32 BLE Keyboard @ ^0.3.2
    adafruit/Adafruit_VL53L0X @ ^1.2.4
