; PlatformIO Project Configuration
; Padel Scoreboard - ESP8266 IR Sensor Button Controller
;
; Upload: Connect ESP8266 via USB, then click Upload in PlatformIO

[env:esp8266]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
lib_deps =
    ESP8266WiFi
    ESP8266HTTPClient
upload_speed = 921600

; Build flags
build_flags =
    -D WIFI_SSID=\"tjiptohome\"
    -D WIFI_PASS=\"chepotz72\"
    -D ANDROID_IP=\"192.168.2.106\"
    -D ANDROID_PORT=8888
