; Project Configuration for Wemos D1 Mini
[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    ESP8266WiFi
    ESP8266HTTPClient
    bblanchon/ArduinoJson @ ^7.0.4

board_build.filesystem = littlefs
